

## Class  `failureException` 
断言失败。

**别名** : [ `tf.compat.v1.test.TestCase.failureException` ](/api_docs/python/tf/test/TestCase/failureException), [ `tf.compat.v2.test.TestCase.failureException` ](/api_docs/python/tf/test/TestCase/failureException)

##  `__init__` 


```
 __init__(
    *args,
    **kwargs
)
 
```

##  `__new__` 


```
 __new__(
    type,
    *args,
    **kwargs
)
 
```

